from __future__ import annotations


CLEAN_AIRPORT_ALIAS_CODE_MAP = {
    "北京": "BJS",
    "首都": "PEK",
    "首都机场": "PEK",
    "首都国际机场": "PEK",
    "大兴": "PKX",
    "大兴机场": "PKX",
    "上海": "SHA",
    "虹桥": "SHA",
    "虹桥机场": "SHA",
    "浦东": "PVG",
    "浦东机场": "PVG",
    "广州": "CAN",
    "深圳": "SZX",
    "成都": "CTU",
    "成都双机场": "CTU",
    "成都两个机场": "CTU",
    "双流": "CTU",
    "天府": "TFU",
    "青岛": "TAO",
    "西安": "XIY",
    "重庆": "CKG",
    "杭州": "HGH",
    "南京": "NKG",
    "武汉": "WUH",
    "天津": "TSN",
    "厦门": "XMN",
    "昆明": "KMG",
    "香港": "HKG",
    "澳门": "MFM",
    "台北": "TPE",
    "新加坡": "SIN",
    "曼谷": "BKK",
    "吉隆坡": "KUL",
    "东京": "TYO",
    "成田": "NRT",
    "羽田": "HND",
    "大阪": "OSA",
    "关西": "KIX",
    "名古屋": "NGO",
    "福冈": "FUK",
    "札幌": "SPK",
    "冲绳": "OKA",
    "首尔": "SEL",
    "仁川": "ICN",
    "金浦": "GMP",
    "釜山": "PUS",
    "济州": "CJU",
    "河内": "HAN",
    "胡志明": "SGN",
    "胡志明市": "SGN",
    "伊尔库茨克": "IKT",
    "海参崴": "VVO",
    "符拉迪沃斯托克": "VVO",
}
